alter table triage_findings add column if not exists evidence_level varchar(32);
alter table triage_findings add column if not exists engine_id varchar(128);
alter table triage_findings add column if not exists engine_version varchar(128);
alter table triage_findings add column if not exists evidence_provider varchar(128);
alter table triage_findings add column if not exists evidence_model varchar(256);
alter table triage_findings add column if not exists model_version varchar(128);
alter table triage_findings add column if not exists prompt_variant varchar(128);
alter table triage_findings add column if not exists prompt_sha256 varchar(64);
alter table triage_findings add column if not exists source_sha256 varchar(64);
alter table triage_findings add column if not exists sarif_sha256 varchar(64);
alter table triage_findings add column if not exists calibrator_id varchar(128);
alter table triage_findings add column if not exists calibration_version varchar(128);
alter table triage_findings add column if not exists calibration_profile varchar(128);
alter table triage_findings add column if not exists calibration_raw_score double precision;
alter table triage_findings add column if not exists evaluated_at timestamp with time zone;
alter table triage_findings add column if not exists raw_false_positive boolean;
alter table triage_findings add column if not exists raw_sanitization_found text;
alter table triage_findings add column if not exists raw_attack_feasible text;
alter table triage_findings add column if not exists raw_evidence_confidence varchar(64);
alter table triage_findings add column if not exists evidence_json text;