apiVersion: apps/v1
kind: Deployment
metadata:
  name: suppression-service-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suppression-service-mock
  template:
    metadata:
      labels:
        app: suppression-service-mock
    spec:
      containers:
        - name: suppression-service-mock
          image: autotriage/suppression-service-mock:latest
          ports:
            - containerPort: 8090
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
