apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autotriage
labels:
  - pairs: {app.kubernetes.io/environment: production}
    includeSelectors: false
images:
  - {name: autotriage/scan-api, newTag: 0.1.0}
  - {name: autotriage/triage-service, newTag: 0.1.0}
  - {name: autotriage/scan-worker-workflow, newTag: 0.1.0}
  - {name: autotriage/scan-worker-light, newTag: 0.1.0}
  - {name: autotriage/scan-worker-filter, newTag: 0.1.0}
  - {name: autotriage/scan-worker-opengrep, newTag: 0.1.0}
patches:
  - target:
      name: "postgres|minio|minio-bucket-init"
    path: remove-incluster-storage.yaml
  - path: configmap.yaml
  - path: scheduling.yaml
  - path: managed-service-egress.yaml
resources:
  - ../../base
  - hpa.yaml
