quarkus.http.port=8080
quarkus.log.redirect-console=false
temporal.target=localhost:7233
temporal.namespace=scan-platform
temporal.tls.enabled=false
temporal.tls.client-cert-path=
temporal.tls.client-key-path=
temporal.tls.server-ca-path=
